"""
Commit `.github/workflows/shipsafe.yml` via GitHub Contents API (connect-repo flow).
Requires OAuth token with contents write (classic: repo scope).
"""

from __future__ import annotations

import base64
import os
from typing import Any
from urllib.parse import quote

import httpx

from backend.services.github_hooks import GITHUB_API, GITHUB_API_VERSION, parse_owner_repo


def _headers(token: str) -> dict[str, str]:
    return {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": GITHUB_API_VERSION,
    }


def public_api_base_for_workflow() -> str:
    """
    Default API URL embedded in the workflow (users can override with repo secret SHIPSAFE_API_URL).
    """
    explicit = (os.environ.get("SHIPSAFE_CI_WORKFLOW_API_URL") or "").strip().rstrip("/")
    if explicit:
        return explicit
    webhook_base = (os.environ.get("SHIPSAFE_WEBHOOK_PUBLIC_URL") or "").strip().rstrip("/")
    if webhook_base:
        return webhook_base
    return "https://shipsafe.dev"


WORKFLOW_PATH = ".github/workflows/shipsafe.yml"


def shipsafe_workflow_yaml(*, default_api_url: str) -> str:
    """GitHub Actions workflow: diff → POST /hooks/prepush on ShipSafe API."""
    # Not an f-string: keep ${{ }} for GitHub Actions expressions verbatim.
    return (
        """# Generated by ShipSafe when you connect this repository.
# Optional repo secrets: SHIPSAFE_API_URL, SHIPSAFE_TOKEN (if your API requires SHIPSAFE_PREPUSH_TOKEN).
name: ShipSafe Security Scan

on:
  pull_request:
  push:

concurrency:
  group: shipsafe-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shipsafe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ShipSafe analysis
        env:
          SHIPSAFE_API_URL: ${{ secrets.SHIPSAFE_API_URL }}
          SHIPSAFE_TOKEN: ${{ secrets.SHIPSAFE_TOKEN }}
          BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          API_URL="${SHIPSAFE_API_URL:-__DEFAULT_API__}"
          ENDPOINT="${API_URL%/}/hooks/prepush"
          if [ "${{ github.event_name }}" = "push" ] && [ "$BASE_SHA" = "0000000000000000000000000000000000000000" ]; then
            BASE_SHA="$(git rev-list --max-parents=0 HEAD | tail -n1)"
          fi
          git fetch -q origin "$BASE_SHA" 2>/dev/null || true
          git fetch -q origin "$HEAD_SHA" 2>/dev/null || true
          DIFF="$(git diff --no-color "$BASE_SHA" "$HEAD_SHA" 2>/dev/null || true)"
          if [ -z "$DIFF" ]; then
            echo "No diff; skipping ShipSafe."
            exit 0
          fi
          TMP="$(mktemp)"
          export GITHUB_REPO
          export HEAD_SHA
          printf '%s' "$DIFF" | python3 -c "import json, os, sys; d = sys.stdin.read(); print(json.dumps({'raw_diff': d, 'repository': os.environ.get('GITHUB_REPO'), 'commit_sha': os.environ.get('HEAD_SHA')}))" > "$TMP"
          if [ -n "${SHIPSAFE_TOKEN:-}" ]; then
            RESP="$(curl -sS -w $'\\n%{http_code}' -X POST "$ENDPOINT" -H "Content-Type: application/json" -H "Authorization: Bearer ${SHIPSAFE_TOKEN}" --data-binary @"$TMP")"
          else
            RESP="$(curl -sS -w $'\\n%{http_code}' -X POST "$ENDPOINT" -H "Content-Type: application/json" --data-binary @"$TMP")"
          fi
          rm -f "$TMP"
          HTTP_BODY="$(printf '%s' "$RESP" | sed '$d')"
          HTTP_CODE="$(printf '%s' "$RESP" | tail -n1)"
          if [ "$HTTP_CODE" != "200" ]; then
            echo "ShipSafe API error HTTP $HTTP_CODE"
            echo "$HTTP_BODY"
            exit 1
          fi
          if ! printf '%s' "$HTTP_BODY" | python3 -c "import sys, json; d=json.load(sys.stdin); sys.exit(0 if d.get('allow_push') else 1)"; then
            echo "ShipSafe blocked: auditor-confirmed findings in this change."
            printf '%s' "$HTTP_BODY" | python3 -c "import sys, json; print(json.dumps(json.load(sys.stdin), indent=2))" || true
            exit 1
          fi
          echo "ShipSafe: no blocking findings."
"""
    ).replace("__DEFAULT_API__", default_api_url)


def _contents_url(owner: str, repo: str, path: str) -> str:
    return f"{GITHUB_API}/repos/{owner}/{repo}/contents/{quote(path, safe='')}"


def _get_contents(
    owner: str, repo: str, path: str, token: str
) -> tuple[dict[str, Any] | None, int]:
    url = _contents_url(owner, repo, path)
    with httpx.Client(timeout=60.0) as client:
        r = client.get(url, headers=_headers(token))
        if r.status_code == 404:
            return None, 404
        r.raise_for_status()
        data = r.json()
        return (data if isinstance(data, dict) else None), r.status_code


def ensure_shipsafe_workflow_file(
    repo_full_name: str,
    token: str,
    *,
    default_api_url: str | None = None,
    force_update: bool = False,
) -> tuple[bool, str | None]:
    """
    Create or update ``.github/workflows/shipsafe.yml``. Skips write if content unchanged (unless force_update).

    Returns (success, error_message).
    """
    owner, repo = parse_owner_repo(repo_full_name)
    base = (default_api_url or public_api_base_for_workflow()).strip().rstrip("/")
    content_raw = shipsafe_workflow_yaml(default_api_url=base)
    content_b64 = base64.b64encode(content_raw.encode("utf-8")).decode("ascii")

    existing, _ = _get_contents(owner, repo, WORKFLOW_PATH, token)
    sha: str | None = None
    if existing and existing.get("sha"):
        sha = str(existing["sha"])
        if not force_update:
            try:
                existing_dec = base64.b64decode(
                    str(existing.get("content", "")).replace("\n", "")
                ).decode("utf-8")
            except ValueError:
                existing_dec = ""
            if existing_dec == content_raw:
                return True, None

    url = _contents_url(owner, repo, WORKFLOW_PATH)
    body: dict[str, Any] = {
        "message": "Add ShipSafe security scan workflow",
        "content": content_b64,
    }
    if sha:
        body["sha"] = sha

    with httpx.Client(timeout=60.0) as client:
        r = client.put(url, headers=_headers(token), json=body)
        try:
            r.raise_for_status()
        except httpx.HTTPStatusError as e:
            msg = (e.response.text or "")[:500]
            return False, f"GitHub API {e.response.status_code}: {msg}"
        except httpx.RequestError as e:
            return False, f"GitHub request failed: {e}"

    return True, None
